---
# YAML documents begin with the document separator ---
 
# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-
 
  # Hosts: where our play will run and options it will run with
  hosts: 10.0.0.1
 
  # Vars: variables that will apply to the play, on all target systems

  # Tasks: the list of tasks that will be executed within the playbook
  tasks:
    - name: Test extra vars
      debug:
        msg: "{{ extra_vars_key }}"

#! see previous lab folder for more info
#! passing variables from a file  yaml & json
#! ansible-playbook variables_playbook.yaml -e @extra_vars_file.yaml
#! ansible-playbook variables_playbook.yaml -e @extra_vars_file.json
# Three dots indicate the end of a YAML document
...
